<html>
<head>
  <title>Senegad</title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">  
  <link rel="stylesheet" type="text/css" href="senegad.css">
  <script type="text/javascript" src="roundedimg.js"></script>
</head>
<body>
<center>

<table cellspacing=0 cellpadding=0 class=main>
<tr>
<td class=leftgradient></td>
<td class=maincontent>
  <table cellspacing=0 cellpadding=0 class=content_table>
    <tr><td style="height:20px;" colspan=9></td></tr>
    <tr><td class=banner colspan=9><img src="images/main_senegad.gif"></td></tr>
    <tr><!-- nav -->
      <td class=link>
        <a href="index.php" class=navlink>
          <img src="images/nav_home.gif"class=navlink></a></td>
      <td class=link>
        <a href="scholarship.php" class=navlink>
          <img src="images/nav_scholarship.gif" class=navlink></a></td>
      <td class=link>
        <a href="youth.php" class=navlink>
          <img src="images/nav_youth.gif" class=navlink></a></td>
      <td class=link>
        <a href="bike.php" class=navlink>
          <img src="images/nav_bike.gif" class=navlink></a></td>
      <td class=link>
        <a href="fundraising.php" class=navlink>
          <img src="images/nav_fundraising.gif" class=navlink></a></td>
      <td class=link>
        <a href="photo.php" class=navlink>
          <img src="images/nav_photo.gif" class=navlink></a></td>
      <td class=link>
        <a href="contact.php" class=navlink>
          <img src="images/nav_contact.gif" class=navlink></a></td>
      <td class=link>
        <a href="phpEventCalendar/" class=navlink>
          <img src="images/nav_calendar.gif" class=navlink></a></td>
      <td class=link>
        <a href="links.php" class=navlink>
          <img src="images/nav_links.gif" class=navlink></a></td>
    </tr>
    <tr>
      <td colspan=9 style="height:100%; vertical-align:top;">